sudo: required
dist: trusty
language: node_js
node_js:
- '8'
git:
  depth: 2
cache:
  directories:
  - node_modules
  - Playground/node_modules
install:
- rm node_modules/@babylonjs/core -f
- rm node_modules/@babylonjs/materials -f
- travis_retry npm install -g gulp@4.0.0
- travis_retry npm install -g typescript
- cd ./Tools/Gulp
- travis_retry npm install
jobs:
  include:
  - stage: BabylonJS Build and test
    env: JOB=WhatsNewUpdate
    script: gulp tests-whatsnew
  - env: JOB=DocumentationCheck
    script: gulp typedoc-check
  - env: JOB=Linting
    script: gulp fullLint
  - env: JOB=Build
    script: gulp typescript-all
  - env: JOB=Tests
    script:
    - export DISPLAY=:99.0
    - export CHROME_BIN=chromium-browser
    - sh -e /etc/init.d/xvfb start
    - sleep 3
    - set -e
    - gulp typescript-all
    - gulp tests-babylon-unit
    - travis_retry gulp tests-validation-virtualscreen
    - travis_retry gulp tests-validation-browserstack
  - env: JOB=ModuleTests
    script:
    - export CHROME_BIN=chromium-browser
    - gulp typescript-all
    - gulp tests-modules
    - gulp deployAndTests-es6Modules
  - env: JOB=ViewerTests
    script:
    - export DISPLAY=:99.0
    - export CHROME_BIN=chromium-browser
    - sh -e /etc/init.d/xvfb start
    - sleep 3
    - set -e
    - gulp typescript-all
    - gulp tests-viewer-unit
    - travis_retry gulp tests-viewer-validation-virtualscreen
    - travis_retry gulp tests-viewer-validation-browserstack
notifications:
  slack:
    secure: YkE09zZ8Bf0olZtogj8rGLSxtWfumGdJbCBNH0Cn16/NYoDDAQgmBlF6NoO0n/Y2zDT1PAkUYym9PM7CYFWMyXdCSASlgAAxbHsTtUKk0Gg34PKQj1VY2JV762mncP9zWe+9zRPVdf21GPwuZtidOH6eMxqpiDIIgo9d1GzZ39Cjt/onBBRrJz2q90V6//u6086+JVMqgC1kr+81f8PB9oS6mvEzZtC7T0XhldbrWPta174DlxQgRybdUSTFEyJhuQYLeHYpFiSddyqfwl9sVxG0h6t+Qr3neEvVNawSYo3j2glQCftC2/MCYaKqEWzcGF+HCz+m1d+7x5LmkqRxIfmjF9b42rzzSiz/MjfISRxQa2uTmvj4OXS1r1Z3Ii0C7krmh1YLA1h+6u/Ot1Z9r/RUnwdw2ljNrZ9nxsNtVphEBcdyAunlReieAGxkxFcOBlB1hVYvFEUqHVVimsoXFvnCg3JYVZZtH5AIH+ereAd8q4bSum9CxEN40SNHJ9Ufrtf/PAJDm/qHn2Q7w5OB5JMlOvUgCWc0svcwxByUgM/PZERc/B6+sS6PE57V5HuHybtvGiwQdVTJue2DWlZ75IgctmzWiRZb06HELuMohpu26MsjPZW/pu/f/MMXq744gXZD4mpD/U0daYVEklzReY6LLSMFjk6UWNJ/DKYmoPg=
env:
  global:
  - secure: lvQBb0VXQiDdgSISvAbsI2W8coPScJ9anLg9DSrVKRq+1cugEKhpWiLq5i/GXbtB9qy9+ecYz5CVWZzxclNLYZIFgbvdJ+POAklxtPg9oVdD/615ndt5Y19yMsH8Pfkjaw/ybbECivjp+WUnJjULX+G0MX1h1f04iXrrttKyG2GfDEdp+YKHT7q1dZB/Nb+Fj5AMJ/baM0lP9Tzww0+/6LBkqGdwqZEBmKXRV/KJ9h32SFMfFPwBz5CYYEVqy0myvxF8qEbb3cG48soeD17ojDWk9HJ4hfvShdhY2NcYXosgGmpZ+1J5HgHUA25PAmXVQQw0wsTndBBDVRNbpjCvJzOMUI1mDyPsekGKzQJBYOtLG7DMqUOIMfz7U+RDNXG1GubzsBIxeONjnYFVpwTaecAi7fgyv1G0zEd6JPATnJLTZIrKodUu8YmY35SvJQPBABIHXjpjrSgMYZzr/yl+lCQtGI5K7lIzl0gwzxPDW63tdPXqNE4+HpGM8UvYwY0RWE9Tl7/PU4lEyQAE6uPHXCu1CVdUhGoLeff7D8py7lNA2qGiBsusuisDA3j9Y9TfcvlZhNJqGj3pb05lfmwrFbMgGzjKvFozarUL2Re00C2q0wMU+V1BZQNPLdxCtK/oKTgv8RqYs9AFjkBEq48lp8GdwP9aYVSkSkfeKMh6zvc=
  - secure: lzob7fhVmI0vNffgJyhM4vZJahJLaafhJxBNyaxncZmiwmpu9cirebJr7sqK5bJaL7HFwjEJF4bmKWah5MWUm+g+PnKTxQYyMF4Ygtyoe17d8ahEI7VK8aoMLSg8x43qwyGMuaAP/Xe2DmyOzXc/9P2QFw9te7PvVb4/CW9XDi41Y0EhcH4hz54T65m67IB2YcHzI9j1TyKhF9SgmZeZdhqywEHJtNQQ3fvMlLCUa0uz9wWQY0Z7JIJSQWzzGkM6YN4HS8TyQiy0fT9r+OVzuXLqSeQTbJLFGFb+UsYVPx5XJ49V3tYiPlleli4SkZcAuWUxtRjUWxjtar04LLK/FhdGIFvGg9EWsjCztekVbe6cYVfSiz/QRwwMnS0orH9ekeUTXss1t1uAUrTw3wERH1dnRb50sd1sSmGA/D0TMJUOElgUHqiVlIa2BhC6OhO4vfIpCUfZnqAVpUGyw/BXfelGQUkglsn0sJUvUbhKSjDWh3lNZRvbAUimJaNbHnmnHMQhhpZuuaRdQybtrEfkbOQ9Kr7CVIzHiKk33Sjut9pfEaw0EUqa+RSzouczL+NEpKSPLplCjXsMKweSgHS7ZTjkZKUXBnyU4pdWKJ0aYeEdFL6WDP5zSuR6lbVVKmQTmmaA/hQJchrYSCQ131zfzLi4rh25IXZrSr+sqH8Zlv8=
